
package vista;

import controller.OptionsController;
import javax.swing.JLabel;
import model.Audio;

/**
 *
 * @author Ivan
 */
public class Options extends javax.swing.JFrame {

    /**
     * Creates new form ReglasEnJuego
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JToggleButton();
        btnMaxVocies = new javax.swing.JButton();
        lbVolume = new javax.swing.JLabel();
        lbVoices = new javax.swing.JLabel();
        lbMusic = new javax.swing.JLabel();
        btnMinVoices = new javax.swing.JButton();
        btnMaxMusic = new javax.swing.JButton();
        btnMinMusic = new javax.swing.JButton();
        lbGif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setBackground(new java.awt.Color(3, 35, 35));
        btnCerrar.setFont(new java.awt.Font("thedarkestpearl", 0, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 140, 40));

        btnMaxVocies.setBackground(new java.awt.Color(5, 37, 37));
        btnMaxVocies.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
        btnMaxVocies.setForeground(new java.awt.Color(255, 255, 255));
        btnMaxVocies.setText("max");
        btnMaxVocies.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMaxVocies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxVociesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaxVocies, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 70, 30));

        lbVolume.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\java\\imagenes\\volume.png")); // NOI18N
        jPanel1.add(lbVolume, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 130, 30));

        lbVoices.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\java\\imagenes\\voices.png")); // NOI18N
        jPanel1.add(lbVoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 90, 60));

        lbMusic.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\java\\imagenes\\music.png")); // NOI18N
        jPanel1.add(lbMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 90, 40));

        btnMinVoices.setBackground(new java.awt.Color(51, 0, 0));
        btnMinVoices.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
        btnMinVoices.setForeground(new java.awt.Color(255, 255, 255));
        btnMinVoices.setText("min");
        btnMinVoices.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMinVoices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinVoicesActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinVoices, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 30));

        btnMaxMusic.setBackground(new java.awt.Color(5, 37, 37));
        btnMaxMusic.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
        btnMaxMusic.setForeground(new java.awt.Color(255, 255, 255));
        btnMaxMusic.setText("max");
        btnMaxMusic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMaxMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaxMusicActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaxMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 70, 30));

        btnMinMusic.setBackground(new java.awt.Color(51, 0, 0));
        btnMinMusic.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
        btnMinMusic.setForeground(new java.awt.Color(255, 255, 255));
        btnMinMusic.setText("min");
        btnMinMusic.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnMinMusic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinMusicActionPerformed(evt);
            }
        });
        jPanel1.add(btnMinMusic, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 70, 30));

        lbGif.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\java\\imagenes\\pcIcon.gif")); // NOI18N
        jPanel1.add(lbGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 260));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed

            OptionsController.cerrarVentana();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnMaxVociesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxVociesActionPerformed
        Audio.volumenUpVoices();
    }//GEN-LAST:event_btnMaxVociesActionPerformed

    private void btnMaxMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaxMusicActionPerformed
      Audio.volumenUpMusic();
    }//GEN-LAST:event_btnMaxMusicActionPerformed

    private void btnMinMusicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinMusicActionPerformed
       Audio.volumenDownMusic();
    }//GEN-LAST:event_btnMinMusicActionPerformed

    private void btnMinVoicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinVoicesActionPerformed
       Audio.volumenDownVoices();
    }//GEN-LAST:event_btnMinVoicesActionPerformed

    public JLabel getLbGif() {
        return lbGif;
    }

    public void setLbGif(JLabel lbGif) {
        this.lbGif = lbGif;
    }

    public JLabel getLbMusic() {
        return lbMusic;
    }

    public void setLbMusic(JLabel lbMusic) {
        this.lbMusic = lbMusic;
    }

    public JLabel getLbVoices() {
        return lbVoices;
    }

    public void setLbVoices(JLabel lbVoices) {
        this.lbVoices = lbVoices;
    }

    public JLabel getLbVolume() {
        return lbVolume;
    }

    public void setLbVolume(JLabel lbVolume) {
        this.lbVolume = lbVolume;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCerrar;
    private javax.swing.JButton btnMaxMusic;
    private javax.swing.JButton btnMaxVocies;
    private javax.swing.JButton btnMinMusic;
    private javax.swing.JButton btnMinVoices;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbGif;
    private javax.swing.JLabel lbMusic;
    private javax.swing.JLabel lbVoices;
    private javax.swing.JLabel lbVolume;
    // End of variables declaration//GEN-END:variables
}
