package vista;

import controller.InicioController;
import controller.ReglasController;

import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;


/**
 *
 * @author Ivan
 */
public class Regla extends javax.swing.JFrame {

    /**
     * Creates new form Regla
     */
    public Regla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbVolver = new javax.swing.JLabel();
        lbIconDavyJones = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        lbImgFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Piratas", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("J");
        jLabel4.setFocusable(false);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 50, 50));

        jLabel3.setFont(new java.awt.Font("Battlesbridge Demo", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Reglas de Juego");
        jLabel3.setFocusable(false);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 80));

        lbVolver.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\volver.png")); // NOI18N
        lbVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbVolverMouseClicked(evt);
            }
        });
        jPanel1.add(lbVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 160, 50));

        lbIconDavyJones.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\davyJonesIcon.png")); // NOI18N
        jPanel1.add(lbIconDavyJones, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 170, 160));

        jPanel2.setBackground(new java.awt.Color(51, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBorder(null);

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(51, 0, 0));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Amontesa", 0, 14)); // NOI18N
        txtArea.setForeground(new java.awt.Color(255, 255, 255));
        txtArea.setRows(5);
        txtArea.setText("\nEn cada ronda, el primer jugador debe anunciar una \ncombinación de dados incluyendo \"cantidad y valor\". \nPor ejemplo, \"tres 4\".\n\n Los jugadores deben continuar diciendo combinaciones de\ndados que superen en cantidad o valor a la combinación \nanunciada anteriormente, o pueden \"desconfiar\" si creen \nque el jugador anterior ha mentido.\n\n Si un jugador \"desconfia\", todos los dados se revelan y se\nhace un recuento.\n Si la combinación anunciada es mayor al recuento, el \njugador que la hizo pierde. Si la combinación  es menor o \nigual al recuento, el jugador que \"desconfió\" pierde.\n\n Ejemplo :\n  Tu mano : 5-5-3-2-1 \n  Mano de Davy Jones : 4-3-3-2-6 \n\n Si apuestas que en total hay \"tres 5\" creyendo que Davy\nJones podría tener al menos un 5, Davy Jones puede\napostar la misma cantidad de dados, pero con un numero\nmás alto \"tres 6\" ó apostar una cantidad mayor al mismo\nvalor \"cuatro 5\" (no importa la cantidad siempre que no\nsupere el total de dados en juego \"diez\") ó puede \"desconfiar\".\n En el último caso perderias la mano por tener solo \"dos 5\".\n \n Espero haya quedado claro. De todas formas, dentro del\njuego tendrás esta misma guia a disposición y habrá un \ncuadro de dialogo que te irá indicando los pasos a seguir.\n  ");
        txtArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtArea.setFocusable(false);
        jScrollPane1.setViewportView(txtArea);
        txtArea.getAccessibleContext().setAccessibleParent(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 460, 370));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 440));

        lbImgFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\tableroJuego.png")); // NOI18N
        jPanel1.add(lbImgFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 440));
        lbImgFondo.getAccessibleContext().setAccessibleParent(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbVolverMouseClicked
        ReglasController.cerrarVentana();
        InicioController.iniciarVentana();
    }//GEN-LAST:event_lbVolverMouseClicked

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JLabel getLbIconDavyJones() {
        return lbIconDavyJones;
    }

    public void setLbIconDavyJones(JLabel lbIconDavyJones) {
        this.lbIconDavyJones = lbIconDavyJones;
    }

    public JLabel getLbImgFondo() {
        return lbImgFondo;
    }

    public void setLbImgFondo(JLabel lbImgFondo) {
        this.lbImgFondo = lbImgFondo;
    }

    public JLabel getLbVolver() {
        return lbVolver;
    }

    public void setLbVolver(JLabel lbVolver) {
        this.lbVolver = lbVolver;
    }

    public JTextArea getTxtArea() {
        return txtArea;
    }

    public void setTxtArea(JTextArea txtArea) {
        this.txtArea = txtArea;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIconDavyJones;
    private javax.swing.JLabel lbImgFondo;
    private javax.swing.JLabel lbVolver;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
