package vista;

import controller.InicioController;
import controller.OptionsController;
import controller.ReglasEnJuegoController;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

import controller.TableroController;

/**
 * @author Ivan
 */
public class Tablero extends javax.swing.JFrame {

    public Tablero() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

	jPanel1 = new javax.swing.JPanel();
	txtDavidJoneSHP = new javax.swing.JTextField();
	btnApostar = new javax.swing.JToggleButton();
	btnDesconfiar = new javax.swing.JToggleButton();
	btnTirarDados = new javax.swing.JToggleButton();
	lbDavyJonesIcon = new javax.swing.JLabel();
	lbNombreJugador1 = new javax.swing.JLabel();
	lbNombreJugador = new javax.swing.JLabel();
	lbImagenJugador = new javax.swing.JLabel();
	lbOptions = new javax.swing.JLabel();
	lbRules = new javax.swing.JLabel();
	lbSalir = new javax.swing.JLabel();
	txtPlayerHP = new javax.swing.JTextField();
	lbDadoRojo1 = new javax.swing.JLabel();
	lbDadoRojo2 = new javax.swing.JLabel();
	lbDadoRojo3 = new javax.swing.JLabel();
	lbDadoRojo4 = new javax.swing.JLabel();
	lbDadoRojo5 = new javax.swing.JLabel();
	lbDadoVerdeTapar = new javax.swing.JLabel();
	jScrollPane1 = new javax.swing.JScrollPane();
	txtArea = new javax.swing.JTextArea();
	lbDadoVerde1 = new javax.swing.JLabel();
	lbDadoVerde2 = new javax.swing.JLabel();
	lbDadoVerde3 = new javax.swing.JLabel();
	lbDadoVerde4 = new javax.swing.JLabel();
	lbDadoVerde5 = new javax.swing.JLabel();
	lbTablero = new javax.swing.JLabel();

	setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
	setResizable(false);

	jPanel1.setBackground(new java.awt.Color(0, 0, 0));
	jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

	txtDavidJoneSHP.setBackground(new java.awt.Color(0, 102, 102));
	txtDavidJoneSHP.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
	txtDavidJoneSHP.setForeground(new java.awt.Color(204, 204, 204));
	txtDavidJoneSHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
	txtDavidJoneSHP.setAutoscrolls(false);
	txtDavidJoneSHP
		.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
			"Hp", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.BELOW_TOP,
			new java.awt.Font("Amontesa", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
	txtDavidJoneSHP.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
	txtDavidJoneSHP.setFocusable(false);
	txtDavidJoneSHP.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		txtDavidJoneSHPActionPerformed(evt);
	    }
	});
	jPanel1.add(txtDavidJoneSHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 310, 40));

	btnApostar.setBackground(new java.awt.Color(2, 30, 26));
	btnApostar.setFont(new java.awt.Font("thedarkestpearl", 0, 14)); // NOI18N
	btnApostar.setForeground(new java.awt.Color(255, 255, 255));
	btnApostar.setText("Apostar");
	btnApostar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	btnApostar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	btnApostar.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		btnApostarActionPerformed(evt);
	    }
	});
	jPanel1.add(btnApostar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 130, 70));

	btnDesconfiar.setBackground(new java.awt.Color(51, 0, 0));
	btnDesconfiar.setFont(new java.awt.Font("thedarkestpearl", 0, 14)); // NOI18N
	btnDesconfiar.setForeground(new java.awt.Color(255, 255, 255));
	btnDesconfiar.setText("Desconfiar");
	btnDesconfiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	btnDesconfiar.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		btnDesconfiarActionPerformed(evt);
	    }
	});
	jPanel1.add(btnDesconfiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 130, 70));

	btnTirarDados.setBackground(new java.awt.Color(2, 30, 26));
	btnTirarDados.setFont(new java.awt.Font("thedarkestpearl", 0, 14)); // NOI18N
	btnTirarDados.setForeground(new java.awt.Color(255, 255, 255));
	btnTirarDados.setText("Tirar dados");
	btnTirarDados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
	btnTirarDados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	btnTirarDados.addActionListener(new java.awt.event.ActionListener() {
	    public void actionPerformed(java.awt.event.ActionEvent evt) {
		btnTirarDadosActionPerformed(evt);
	    }
	});
	jPanel1.add(btnTirarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 130, 70));

	lbDavyJonesIcon.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\davyJones.png")); // NOI18N
	lbDavyJonesIcon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
	jPanel1.add(lbDavyJonesIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 150, 150));

	lbNombreJugador1.setBackground(new java.awt.Color(0, 0, 0));
	lbNombreJugador1.setFont(new java.awt.Font("BlackKnightFLF", 2, 55)); // NOI18N
	lbNombreJugador1.setForeground(new java.awt.Color(255, 153, 0));
	lbNombreJugador1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	lbNombreJugador1.setText("Davy Jones");
	lbNombreJugador1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	jPanel1.add(lbNombreJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 220, 60));

	lbNombreJugador.setBackground(new java.awt.Color(0, 0, 0));
	lbNombreJugador.setFont(new java.awt.Font("BlackKnightFLF", 2, 55)); // NOI18N
	lbNombreJugador.setForeground(new java.awt.Color(255, 153, 0));
	lbNombreJugador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	lbNombreJugador.setText("Player");
	lbNombreJugador.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
	jPanel1.add(lbNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 190, 60));

	lbImagenJugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
	lbImagenJugador.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\jack2.png")); // NOI18N
	lbImagenJugador.setBorder(javax.swing.BorderFactory.createEtchedBorder());
	jPanel1.add(lbImagenJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 150));

	lbOptions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	lbOptions.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\options.png")); // NOI18N
	lbOptions.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	lbOptions.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		lbOptionsMouseClicked(evt);
	    }
	});
	jPanel1.add(lbOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 100, 40));

	lbRules.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\rules.png")); // NOI18N
	lbRules.setVerticalAlignment(javax.swing.SwingConstants.TOP);
	lbRules.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	lbRules.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		lbRulesMouseClicked(evt);
	    }
	});
	jPanel1.add(lbRules, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 80, 30));

	lbSalir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
	lbSalir.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\Salir.png")); // NOI18N
	lbSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
	lbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
	    public void mouseClicked(java.awt.event.MouseEvent evt) {
		lbSalirMouseClicked(evt);
	    }
	});
	jPanel1.add(lbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 110, 40));

	txtPlayerHP.setBackground(new java.awt.Color(102, 0, 0));
	txtPlayerHP.setFont(new java.awt.Font("thedarkestpearl", 0, 18)); // NOI18N
	txtPlayerHP.setForeground(new java.awt.Color(204, 204, 204));
	txtPlayerHP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
	txtPlayerHP.setAutoscrolls(false);
	txtPlayerHP
		.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(),
			"Hp", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_BOTTOM,
			new java.awt.Font("Amontesa", 1, 14), new java.awt.Color(204, 204, 204))); // NOI18N
	txtPlayerHP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
	txtPlayerHP.setFocusable(false);
	jPanel1.add(txtPlayerHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 310, 40));

	lbDadoRojo1.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\dadoRojo1\\2.png")); // NOI18N
	jPanel1.add(lbDadoRojo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbDadoRojo2.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\dadoRojo2\\4.png")); // NOI18N
	jPanel1.add(lbDadoRojo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbDadoRojo3.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\dadoRojo3\\4.png")); // NOI18N
	jPanel1.add(lbDadoRojo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbDadoRojo4.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\dadoRojo4\\6.png")); // NOI18N
	jPanel1.add(lbDadoRojo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbDadoRojo5.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\dadoRojo5\\2.png")); // NOI18N
	jPanel1.add(lbDadoRojo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbDadoVerdeTapar.setFocusable(false);
	lbDadoVerdeTapar.setInheritsPopupMenu(false);
	lbDadoVerdeTapar.setVerifyInputWhenFocusTarget(false);
	jPanel1.add(lbDadoVerdeTapar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 440));

	jScrollPane1.setBackground(new java.awt.Color(51, 0, 0));
	jScrollPane1.setForeground(new java.awt.Color(255, 255, 255));

	txtArea.setBackground(new java.awt.Color(51, 0, 0));
	txtArea.setColumns(20);
	txtArea.setFont(new java.awt.Font("Amontesa", 0, 14)); // NOI18N
	txtArea.setForeground(new java.awt.Color(204, 204, 204));
	txtArea.setRows(5);
	txtArea.setText(
		"Para comenzar a jugar presiona  \"tirar dados\" y luego has una apuesta con\nel boton \"apostar\". \n Tanto tú como Davy Jones tienen una barra de Hp que irá bajando a medida que\nvayan perdiendo sus apuestas. El ganador será quien se quede sin Hp");
	txtArea.setAutoscrolls(false);
	txtArea.setFocusable(false);
	jScrollPane1.setViewportView(txtArea);

	jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 660, 140));
	jPanel1.add(lbDadoVerde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));
	jPanel1.add(lbDadoVerde2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));
	jPanel1.add(lbDadoVerde3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));
	jPanel1.add(lbDadoVerde4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));
	jPanel1.add(lbDadoVerde5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 920, 480));

	lbTablero.setIcon(new javax.swing.ImageIcon(
		"C:\\Users\\Ivan\\Spring Boot\\workspace-spring-tool-suite-4-4.17.1.RELEASE\\juego-dados-piratas-del-caribe\\src\\main\\resources\\imagenes\\tableroJuego.png")); // NOI18N
	lbTablero.setBorder(null);
	jPanel1.add(lbTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 920, 500));

	javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	getContentPane().setLayout(layout);
	layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
		jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
	layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
		jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

	pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDesconfiarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnDesconfiarActionPerformed
	if (TableroController.getPlayer().getDados() == null) {
	    Icon icon = new ImageIcon(getClass().getResource("/imagenes/DavyJonesIcon2.png"));
	    JOptionPane.showMessageDialog(rootPane, "No se puede desconfiar.",
		    "Debes tirar los dados ó realizar una apuesta.", JOptionPane.NO_OPTION, icon);
	} else {
	    TableroController.btnDesconfiar();
	}

    }// GEN-LAST:event_btnDesconfiarActionPerformed

    private void txtDavidJoneSHPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtDavidJoneSHPActionPerformed
	// TODO add your handling code here:
    }// GEN-LAST:event_txtDavidJoneSHPActionPerformed

    private void lbRulesMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbRulesMouseClicked
	ReglasEnJuegoController.iniciarVentana();
    }// GEN-LAST:event_lbRulesMouseClicked

    private void lbSalirMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbSalirMouseClicked
	TableroController.cerrarVentana();
	InicioController.iniciarVentana();
    }// GEN-LAST:event_lbSalirMouseClicked

    private void lbOptionsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lbOptionsMouseClicked
	OptionsController.iniciarVentana();
    }// GEN-LAST:event_lbOptionsMouseClicked

    private void btnTirarDadosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnTirarDadosActionPerformed

	if (TableroController.getPlayer().getDados() != null) {
	    Icon icon = new ImageIcon(getClass().getResource("/imagenes/DavyJonesIcon2.png"));
	    JOptionPane.showMessageDialog(rootPane, "Debes completar la mano para volver a tirar los dados",
		    "La mano termina cuando uno de los dos jugadores desconfie de la apuesta del otro",
		    JOptionPane.NO_OPTION, icon);
	} else {
	    this.lbDadoVerdeTapar.setSize(920, 440);
	    this.lbDadoVerdeTapar.setIcon(new ImageIcon(getClass().getResource("/imagenes/taparDados.png")));
	    TableroController.iniciarAudioDados();
	    TableroController.setLabelsDados(TableroController.getPlayer(), "rojo");
	    TableroController.setLabelsDados(TableroController.getDavyJones(), "verde");
	}

    }// GEN-LAST:event_btnTirarDadosActionPerformed

    private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnApostarActionPerformed

	if (TableroController.getPlayer().getDados() == null) {
	    Icon icon = new ImageIcon(getClass().getResource("/imagenes/DavyJonesIcon2.png"));
	    JOptionPane.showMessageDialog(rootPane, "No puedes iniciar una apuesta",
		    "Presiona el boton tirar los dados para comenzar el juego.", JOptionPane.NO_OPTION, icon);
	} else {
	    TableroController.btnApostar();
	}

    }// GEN-LAST:event_btnApostarActionPerformed

    private void txtPlayerHPActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtPlayerHPActionPerformed

    }// GEN-LAST:event_txtPlayerHPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnApostar;
    private javax.swing.JToggleButton btnDesconfiar;
    private javax.swing.JToggleButton btnTirarDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbDadoRojo1;
    private javax.swing.JLabel lbDadoRojo2;
    private javax.swing.JLabel lbDadoRojo3;
    private javax.swing.JLabel lbDadoRojo4;
    private javax.swing.JLabel lbDadoRojo5;
    private javax.swing.JLabel lbDadoVerde1;
    private javax.swing.JLabel lbDadoVerde2;
    private javax.swing.JLabel lbDadoVerde3;
    private javax.swing.JLabel lbDadoVerde4;
    private javax.swing.JLabel lbDadoVerde5;
    private javax.swing.JLabel lbDadoVerdeTapar;
    private javax.swing.JLabel lbDavyJonesIcon;
    private javax.swing.JLabel lbImagenJugador;
    private javax.swing.JLabel lbNombreJugador;
    private javax.swing.JLabel lbNombreJugador1;
    private javax.swing.JLabel lbOptions;
    private javax.swing.JLabel lbRules;
    private javax.swing.JLabel lbSalir;
    private javax.swing.JLabel lbTablero;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtDavidJoneSHP;
    private javax.swing.JTextField txtPlayerHP;
    // End of variables declaration//GEN-END:variables

    public JLabel getLbDadoRojo1() {
	return lbDadoRojo1;
    }

    public void setLbDadoRojo1(JLabel lbDado1) {
	this.lbDadoRojo1 = lbDado1;
    }

    public JLabel getLbDadoRojo2() {
	return lbDadoRojo2;
    }

    public void setLbDadoRojo2(JLabel lbDado2) {
	this.lbDadoRojo2 = lbDado2;
    }

    public JLabel getLbDadoRojo3() {
	return lbDadoRojo3;
    }

    public void setLbDadoRojo3(JLabel lbDado3) {
	this.lbDadoRojo3 = lbDado3;
    }

    public JLabel getLbDadoRojo4() {
	return lbDadoRojo4;
    }

    public JLabel getLbDadoRojo5() {
	return lbDadoRojo5;
    }

    public void setLbDadoRojo5(JLabel lbDado5) {
	this.lbDadoRojo5 = lbDado5;
    }

    public void setLbDadoRojo4(JLabel lbDado4) {
	this.lbDadoRojo4 = lbDado4;
    }

    public JLabel getLbDadoVerde1() {
	return lbDadoVerde1;
    }

    public void setLbDadoVerde1(JLabel lbDadoVerde1) {
	this.lbDadoVerde1 = lbDadoVerde1;
    }

    public JLabel getLbDadoVerde2() {
	return lbDadoVerde2;
    }

    public void setLbDadoVerde2(JLabel lbDadoVerde2) {
	this.lbDadoVerde2 = lbDadoVerde2;
    }

    public JLabel getLbDadoVerde3() {
	return lbDadoVerde3;
    }

    public void setLbDadoVerde3(JLabel lbDadoVerde3) {
	this.lbDadoVerde3 = lbDadoVerde3;
    }

    public JLabel getLbDadoVerde4() {
	return lbDadoVerde4;
    }

    public void setLbDadoVerde4(JLabel lbDadoVerde4) {
	this.lbDadoVerde4 = lbDadoVerde4;
    }

    public JLabel getLbDadoVerde5() {
	return lbDadoVerde5;
    }

    public void setLbDadoVerde5(JLabel lbDadoVerde5) {
	this.lbDadoVerde5 = lbDadoVerde5;
    }

    public JLabel getLbDadoVerdeTapar() {
	return lbDadoVerdeTapar;
    }

    public void setLbDadoVerdeTapar(JLabel lbDadoVerdeTapar) {
	this.lbDadoVerdeTapar = lbDadoVerdeTapar;
    }

    public JLabel getLbImagenJugador() {
	return lbImagenJugador;
    }

    public void setLbImagenJugador(JLabel lbImagenJugador) {
	this.lbImagenJugador = lbImagenJugador;
    }

    public JLabel getLbNombreJugador() {
	return lbNombreJugador;
    }

    public void setLbNombreJugador(JLabel lbNombreJugador) {
	this.lbNombreJugador = lbNombreJugador;
    }

    public JLabel getLbOptions() {
	return lbOptions;
    }

    public void setLbOptions(JLabel lbOptions) {
	this.lbOptions = lbOptions;
    }

    public JLabel getLbRules() {
	return lbRules;
    }

    public void setLbRules(JLabel lbRules) {
	this.lbRules = lbRules;
    }

    public JLabel getLbSalir() {
	return lbSalir;
    }

    public void setLbSalir(JLabel lbSalir) {
	this.lbSalir = lbSalir;
    }

    public JLabel getLbTablero() {
	return lbTablero;
    }

    public void setLbTablero(JLabel lbTablero) {
	this.lbTablero = lbTablero;
    }

    public JLabel getLbDavyJonesIcon() {
	return lbDavyJonesIcon;
    }

    public void setLbDavyJonesIcon(JLabel lbDavyJonesIcon) {
	this.lbDavyJonesIcon = lbDavyJonesIcon;
    }

    public JTextArea getTxtArea() {
	return txtArea;
    }

    public void setTxtArea(JTextArea txtArea) {
	this.txtArea = txtArea;
    }

    public JTextField getTxtDavidJones1() {
	return txtDavidJoneSHP;
    }

    public void setTxtDavidJones1(JTextField txtDavidJones1) {
	this.txtDavidJoneSHP = txtDavidJones1;
    }

    public JTextField getTxtDavidJoneSHP() {
	return txtDavidJoneSHP;
    }

    public void setTxtDavidJoneSHP(JTextField txtDavidJoneSHP) {
	this.txtDavidJoneSHP = txtDavidJoneSHP;
    }

    public JTextField getTxtPlayerHP() {
	return txtPlayerHP;
    }

    public void setTxtPlayerHP(JTextField txtPlayerHP) {
	this.txtPlayerHP = txtPlayerHP;
    }

}
